Adding new messages
rticommunity/rticonnextdds-logparser pull request #1
Opened 2016-10-24 20:36 UTC by iblancasa

* Parsing some messages from the initialiazation of Connext DDS
* Parsing other messages related to:
  * Skipped interfaces
  * Inconsistent transport/discovery configuration

2016-10-25 09:59 UTC, pleonex requested changes

2016-10-25 09:59 UTC, pleonex commented on src/initialization/logs.py
> +    regex.append([initialization.on_no_environment_ndds_qos_profiles,
Check if the `RTIOsapi_envVarOrFileGet` expression are parsed in the config module.

2016-10-25 09:59 UTC, pleonex commented on src/initialization/logs.py
> +    regex.append([debug.on_ignored_message,
Move the ignore messages to the debug module.

2016-10-25 09:59 UTC, pleonex commented on src/events/logs.py
> +                  r"\[D0000\|ENABLE\]DDS_DomainParticipant_enableI:Automatic participant index failed to initialize\. PLEASE VERIFY CONSISTENT TRANSPORT \/ DISCOVERY CONFIGURATION\."])
Remove the context `[D0000|ENABLE]` from the regular expression. They could not appear in some situations.

2016-10-25 09:59 UTC, pleonex commented on src/events/events.py
> +    log_event("Skipped interface: %s" % match[0],state,2)
Missing spaces in the arguments. Try running pylama on the new code.

2016-10-25 09:59 UTC, pleonex commented on src/initialization/logs.py
> +
Too many blank lines

2016-10-25 09:59 UTC, pleonex commented on src/initialization/logs.py
> +# Log Parser for RTI Connext.
I would say to add these logs into the config module. They are *similar* and at the moment there isn't enough logs to split into a new module.

2016-10-25 09:59 UTC, pleonex commented on src/logger.py
> +def log_init(text, state, level=2):
Merge this function with `log_cfg`, setting the default verbosity to 2 by default.

2016-10-26 19:57 UTC, iblancasa commented
I think that all is OK now

2016-10-26 20:28 UTC, pleonex requested changes

2016-10-26 20:28 UTC, pleonex commented on src/events/logs.py
> +                  r"\[D0000\|ENABLE\]NDDS_Transport_UDPv4_query_interfaces:" +
Remove the context log `[D000|ENABLE]` from the regex.

2016-10-26 20:28 UTC, pleonex commented on src/events/logs.py
> +                  r"RTIOsapi_envVarOrFileGet:environment variable " +
I recommend you to make these expressions general by using a capture group for the env var or file names. Like  `RTIOsapi_envVarOrFileGet: file (\w+) not found"`

2016-10-26 21:50 UTC, iblancasa commented
I think this is de last :+1: I squashed all the commits into one... because there are some dummy commits

2016-10-29 18:13 UTC, iblancasa commented
And... now?

2016-10-31 10:06 UTC, pleonex approved these changes
Looks good. Thanks!

2016-10-31 10:07 UTC, merged