Logger refactor
rticommunity/rticonnextdds-logparser pull request #23
Opened 2016-12-30 14:50 UTC by iblancasa

2016-12-30 14:52 UTC, iblancasa commented
Part of #22

2016-12-31 02:06 UTC, pleonex requested changes
You need to update the log function example in the README file.

2016-12-31 02:06 UTC, pleonex commented on logparser/logger.py
> +        ignore
Typo line

2016-12-31 02:06 UTC, pleonex commented on logparser/logger.py
> +        onlyIf (:obj:`compiled re`): show only
The description fits in one line.

2016-12-31 02:06 UTC, pleonex commented on logparser/logger.py
> +    def setVerbosity(self, value):
*getters* and *setters* are not recommended in python. We can start using the attribute directly and later move to property if needed. I recommend this article: https://dirtsimple.org/2004/12/python-is-not-java.html

2016-12-31 02:06 UTC, pleonex commented on logparser/logs/events/events.py
> +    print("sdfsdfsd")
I ***think*** you forgot to remove this line

2016-12-31 02:06 UTC, pleonex commented on logparser/logs/events/events.py
> +    logger.error("[LP-15] Cannot delete %s FlowControllers" % (num_flowcontrol)
The `+` should be the latest symbol in a line when splitting a string. If it line doesn't fit because of it, move words to the next one.  For instance:
```
logger.error("[LP-15] Cannot delete %s " % (num_flowcontrol) +
             "FlowControllers from delete_contained_entities")
```

2016-12-31 02:06 UTC, pleonex commented on logparser/logs/events/events.py
> +    logger.process("[LP-18] Cannot match remote entity in topic '%s': "
This is a log *error* not a *process*.

2016-12-31 02:06 UTC, pleonex commented on logparser/logs/network/network.py
> +    logger.wrning("[LP-9] Cannot drop unregistered instance, missing ACKs", 1)
You are missing an `a` in *warning*

2017-01-03 08:58 UTC, iblancasa commented on logparser/logger.py
> +        onlyIf (:obj:`compiled re`): show only
The description is larger than 80 chars... Pylama :(

2017-01-03 09:10 UTC, iblancasa commented on logparser/logger.py
> +    def setVerbosity(self, value):
I think that this is not a good pattern to follow... We are using classes and one of their objectives is "encapsulation". We don't need these attributes as public... What about if we want to change something in the future? If we use the attributes directly, we will need to change a lot of lines of code...
Also, I think it is more readable.

What about properties? This is the "pythonic" way

2017-01-03 09:10 UTC, iblancasa commented on logparser/logs/events/events.py
> +    print("sdfsdfsd")
Sure? :smile:

2017-01-03 09:45 UTC, pleonex commented on logparser/logger.py
> +    def setVerbosity(self, value):
I prefer properties too.

2017-01-03 10:12 UTC, pleonex commented on logparser/logger.py
> +        onlyIf (:obj:`compiled re`): show only
What about this one which is similar to the *highlight* description?
*onlyIf (:obj:`compiled re`): show only regex matched logs*

2017-01-04 16:26 UTC, pleonex requested changes
You are missing the changes in the README.

2017-01-04 16:26 UTC, pleonex commented on logparser/logger.py
> +            value (bool): show inline
Copy/Paste typo

2017-01-04 16:26 UTC, pleonex commented on logparser/logger.py
> +            Requires self._showColors = True
I think we shouldn't expose *private* variables in the documentation, right?

2017-01-04 16:26 UTC, pleonex commented on logparser/logger.py
> +        state (:obj:`list` of `str`): information about the parse process
`state` is a dictionary, not a list.

2017-01-04 16:26 UTC, pleonex commented on logparser/logger.py
> +        onlyIf (:obj:compiled re): show only regex matched logs
Missing *`* for *compiled re*

2017-01-04 16:26 UTC, pleonex commented on logparser/logger.py
> +        """Set  the verbosity level.
There are two spaces between *Set* and *the*

2017-01-04 16:26 UTC, pleonex commented on logparser/logger.py
> +            value (bool): show inline
show network logs

2017-01-04 16:26 UTC, pleonex commented on logparser/logger.py
> +            :obj:`compiled re`: he set regex to match logs
Missing *t* in *the*

2017-01-04 16:40 UTC, iblancasa commented on logparser/logger.py
> +            value (bool): show inline
?

2017-01-05 15:10 UTC, pleonex approved these changes
Good work!

2017-01-05 15:11 UTC, merged